name: Inker
version: "0.5.0"
slug: inker
description: TRMNL self host implementation
url: https://github.com/wojooo/inker

arch:
  - aarch64
  - amd64

startup: services
boot: auto
init: false

image: docker.io/wojooo/inker

ports:
  80/tcp: 15297

map:
  - addon_config:rw

environment:
  TZ: "{options.tz}"
  ADMIN_PIN: "1111"