name: Atvloadly
version: "1.0.0"
slug: atvloadly
description: Apple TV sideloading server

arch:
  - aarch64
  - amd64

startup: services
boot: auto
init: false

image: bitxeno/atvloadly

ports:
  80/tcp: 5533

map:
  - data:rw

host_dbus: true
host_network: true

apparmor: false
